apiVersion: apps/v1
kind: Deployment
metadata:
  name: covaiml-deployment
spec:
  selector:
    matchLabels:
      app: covaiml
  replicas: 3
  template:
    metadata:
      labels:
        app: covaiml
    spec:
      containers:
      - name: covaiml
        image: "sromano41/covai19ml:0.0.2"
        env:
        - name: "PORT"
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: covaiml-lb-service
spec:
  type: LoadBalancer
  selector:
    app: covaiml
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000