swagger: "2.0"
info:
  description: "This is the covAI-19 API Swagger file."
  version: "1.0.0"
  title: "Swagger covAI-19"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "s.romano1992@gmail.com"
host: "35.238.217.244:8000"
basePath: "/"
tags:
- name: "predict"
  description: "Get the predictions for number of deaths, recovered and confirmed Covid-19 cases for the next week"
  externalDocs:
    description: "Find out more about the project"
    url: "https://medium.com/@s.romano1992/covai-19-covid-19-diffusion-prediction-in-italy-part-1-e7d20f653b46"
schemes:
- "http"
paths:
  /predict:
    post:
      tags:
      - "predict"
      summary: "Get the predictions for number of deaths, recovered and confirmed Covid-19 cases for the next week"
      description: ""
      operationId: "predict"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "country"
        description: "Country to predict"
        required: true
        schema:
          $ref: "/#/country"
      responses:
        200:
          description: "OK"
definitions:
  Order:
    type: "country"
    properties:
      status:
        type: "string"
        description: "Country to predict"
        enum:
        - "Italy"
        - "China"
  ApiResponse:
    type: "object"
    properties:
      author:
        type: "string"
      chart:
        type: "string"
        format: "base64"
      x_plot:
        type: "string"
      y_confirmed:
        type: "string"
      y_confirmed_predicted_plot:
        type: "string"
      y_death:
        type: "string"
      y_deaths_predicted_plot:
        type: "string"
      y_recovered:
        type: "string"
      y_recovered_predicted_plot:
        type: "string"
externalDocs:
  description: "Find out more about covAI-19"
  url: "https://medium.com/@s.romano1992/covai-19-covid-19-diffusion-prediction-in-italy-part-1-e7d20f653b46"